services:
  otto:
    build: .
    expose:
      - '8000'
    environment:
      HOST: '0.0.0.0'
      PORT: '8000'
    restart: unless-stopped
    networks:
      coolify: null

networks:
  coolify:
    external: true
    name: coolify
